const SCHEDULE = {
Monday:[['7:00 AM – 9:00 AM','KRG-BREAKFAST SHOW','Sandile “Taka’Q” Buzani'],['9:00 AM – 12:00 PM','LET’S TALK','DJ Andy & DJ Ntosh'],['12:00 PM – 3:00 PM','LUNCHTIME & CHILL','A Kelly & Mr Lux'],['3:00 PM – 6:00 PM','KRG-DRIVE SHOW','Zikhali'],['6:00 PM – 7:00 PM','EZEMFUNDO','Lady-Tee'],['7:00 PM – 9:00 PM','YOUR VOICE','L Budaza “Brother B”']],
Tuesday:[['7:00 AM – 9:00 AM','KRG-BREAKFAST SHOW','Sandile “Taka’Q” Buzani'],['9:00 AM – 12:00 PM','THE HEALTH CORNER','Lady Prophet Nomah & Co-Host Str. Pumela Nteyi'],['12:00 PM – 3:00 PM','LUNCHTIME & CHILL','A Kelly & Mr Lux'],['3:00 PM – 6:00 PM','KRG-DRIVE SHOW','Zikhali'],['6:00 PM – 8:00 PM','THE SUNSET CONNECXION','Lisa K'],['8:00 PM – 10:00 PM','INCOKO','Tulani Klaas']],
Wednesday:[['7:00 AM – 9:00 AM','KRG-BREAKFAST SHOW','Sandile “Taka’Q” Buzani'],['9:00 AM – 12:00 PM','STILL STANDING','Tuni Cwerhakazi'],['12:00 PM – 3:00 PM','LUNCHTIME & CHILL','A Kelly & Mr Lux'],['3:00 PM – 6:00 PM','KRG-DRIVE SHOW','Zikhali'],['6:00 PM – 7:00 PM','EZEMFUNDO','Lady-Tee'],['7:00 PM – 9:00 PM','YOUR VOICE','L Budaza “Brother B”']],
Thursday:[['7:00 AM – 9:00 AM','KRG-BREAKFAST SHOW','Sandile “Taka’Q” Buzani'],['9:00 AM – 12:00 PM','OPEN PROGRAMMING','—'],['12:00 PM – 3:00 PM','UTHIXO UNAKHO / GOD IS ABLE','MaGaba'],['3:00 PM – 6:00 PM','KRG-DRIVE SHOW','Zikhali'],['6:00 PM – 8:00 PM','LET THE MARRIAGE LIVE','Apstl & Lady Apstl Ngaka']],
Friday:[['7:00 AM – 9:00 AM','KRG-BREAKFAST SHOW','Sandile “Taka’Q” Buzani'],['9:00 AM – 12:00 PM','THE MOMO SHOW','Sista Sbosh'],['12:00 PM – 3:00 PM','LUNCHTIME & CHILL','A Kelly & Mr Lux'],['3:00 PM – 6:00 PM','KRG-DRIVE SHOW','Zikhali'],['6:00 PM – 9:00 PM','SPORT UNPLUGGED','Thando Damane']],
Saturday:[['6:00 AM – 9:00 AM','KRG WEEKEND BREAKFAST SHOW','Thando Damane'],['9:00 AM – 10:00 AM','OPEN PROGRAMMING','—'],['10:00 AM – 1:00 PM','ISINGQI SAKWANTU','Mandi-Dee & Thee'],['1:00 PM – 3:00 PM','KRG TOP20 COUNTDOWN','Sista Sbosh & Lisa-K'],['3:00 PM – 5:00 PM','KRG GOOD-TIMES','DJ Andy & DJ Ntosh'],['5:00 PM – 8:00 PM','CHILL & CONNECT','Msiyana & Lerato']],
Sunday:[['7:00 AM – 9:00 AM','UYEHOVA UNDIKHUMBULE NAM','Mr Z Ntyuku & Bishop Duna'],['9:00 AM – 11:00 AM','YENYUK’ INTABA MZAYONI','Mr S Yisaka & Bishop Pram'],['11:00 AM – 1:00 PM','SOULFUL SESSIONS','Siya Jilaji'],['1:00 PM – 4:00 PM','THE LOVE THERAPY','Morgan C'],['4:00 PM – 6:00 PM','INDUMISO ZASEKHAYA','Mr V'],['6:00 PM – 8:00 PM','UKUFEZWA KWAMADINGA','Apstl & Lady Apstl Ngaka']]
};
const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const STREAM_URL='https://stream.zeno.fm/uoscm48onclvv';
let audio=null,player=null;

const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function initials(name){return name.replace(/[“”‘’]/g,'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function currentPage(){return location.pathname.split('/').pop()||'index.html'}
function shell(){
 const current=currentPage();
 const h=document.getElementById('site-header');
 if(h)h.innerHTML=`<header class="site-header"><div class="container nav"><a class="brand" href="index.html"><img src="assets/kariega-logo.png" alt="Kariega Online Radio"><span>Kariega Online Radio</span></a><button class="menu" id="menuBtn" aria-label="Open navigation">☰</button><nav class="nav-links" id="navLinks"><a class="${current==='index.html'?'active':''}" href="index.html">Home</a><a class="${current==='schedule.html'?'active':''}" href="schedule.html">Programme</a><a class="${current==='presenters.html'?'active':''}" href="presenters.html">Presenters</a><a class="${current==='partners.html'?'active':''}" href="partners.html">Partners</a><a class="${current==='about.html'?'active':''}" href="about.html">About</a><a class="${current==='contact.html'?'active':''}" href="contact.html">Contact</a><a class="${current==='join.html'?'active':''}" href="join.html">Join Us</a><button class="nav-live" data-play>▶ Live</button></nav></div></header>`;
 document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('navLinks').classList.toggle('open'));
 const f=document.getElementById('site-footer');
 if(f)f.innerHTML=`<footer class="footer"><div class="container footer-grid"><div><img class="footer-logo" src="assets/kariega-logo.png" alt="Kariega Online Radio"><p><strong>The Voice of Kariega.</strong><br>Singabahlobo Bakho.<br>Proudly Local. Proudly Kariega.</p></div><div><h4>EXPLORE</h4><a href="schedule.html">Weekly Programme</a><a href="presenters.html">Presenters</a><a href="partners.html">Partners</a><a href="about.html">About Us</a><a href="join.html">Join Our Team</a></div><div><h4>CONNECT</h4><a href="mailto:krg.onlineradio@gmail.com">krg.onlineradio@gmail.com</a><a href="mailto:music.krgonlineradio@gmail.com">Music Submissions</a><a href="mailto:info.krgonlineradio@gmail.com">Join Our Team</a><a href="tel:+27691741089">Studio / WhatsApp: 069 174 1089</a></div><div><h4>LISTEN</h4><button class="footer-live" data-play>▶ Listen Live</button><a href="${STREAM_URL}" target="_blank" rel="noopener">Open Zeno.fm stream ↗</a><span class="social-handle">@KariegaOnlineRadio</span></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Kariega Online Radio</span><span>Powered by <a href="https://slabb-digital-group.github.io/SLABB-Digital-Group-web/" target="_blank" rel="noopener">SLABB Digital Group</a></span></div></footer>`;
}
function ensurePlayer(){
 if(audio)return;
 audio=new Audio(STREAM_URL);audio.preload='none';
 audio.addEventListener('playing',updatePlayer);audio.addEventListener('pause',updatePlayer);audio.addEventListener('waiting',updatePlayer);
 audio.addEventListener('error',()=>{updatePlayer();document.querySelectorAll('.player-title').forEach(x=>x.textContent='Stream unavailable — try again');});
 player=document.createElement('aside');player.className='player';player.innerHTML=`<button class="player-toggle" id="playerToggle" aria-label="Play live stream">▶</button><div><small>LIVE STREAM</small><strong class="player-title">Kariega Online Radio</strong><span id="playerState">Ready to play</span></div><a href="${STREAM_URL}" target="_blank" rel="noopener">Open stream ↗</a>`;document.body.appendChild(player);
 document.getElementById('playerToggle').addEventListener('click',togglePlayer);
}
async function togglePlayer(){ensurePlayer();try{if(audio.paused)await audio.play();else audio.pause()}catch{document.getElementById('playerState').textContent='Tap Listen Live again to start'}updatePlayer()}
function updatePlayer(){const playing=audio&&!audio.paused;const btn=document.getElementById('playerToggle');if(btn)btn.textContent=playing?'❚❚':'▶';document.querySelectorAll('[data-play]').forEach(b=>b.textContent=playing?(b.classList.contains('nav-live')?'❚❚ Live':'❚❚ Playing Live'):(b.classList.contains('nav-live')?'▶ Live':'▶ Listen Live'));document.querySelectorAll('#liveMessage').forEach(x=>x.textContent=playing?'You are listening live.':'The Voice of Kariega • Live online');const s=document.getElementById('heroStatus');if(s)s.textContent=playing?'You are listening live.':'Ready to stream live';const ps=document.getElementById('playerState');if(ps)ps.textContent=playing?'Streaming live now':'Ready to play'}
function parseTime(t){const m=t.match(/(\d+):?(\d+)?\s*(AM|PM)/i);let h=Number(m[1]),min=Number(m[2]||0);const ap=m[3].toUpperCase();if(ap==='PM'&&h!==12)h+=12;if(ap==='AM'&&h===12)h=0;return h*60+min}
function row(item,active=false){return `<article class="show-row ${active?'active':''}"><div class="show-time">${esc(item[0])}</div><div class="show-main"><strong>${esc(item[1])}</strong><span>${esc(item[2])}</span></div>${active?'<span class="on-now">ON AIR</span>':''}</article>`}
function todaysShows(){const day=DAYS[new Date().getDay()],items=SCHEDULE[day]||[],now=new Date().getHours()*60+new Date().getMinutes();let active=-1;items.forEach((x,i)=>{const p=x[0].split(' – ');if(p.length===2&&now>=parseTime(p[0])&&now<parseTime(p[1]))active=i});return{day,items,active}}
function renderToday(){const el=document.getElementById('todaySchedule');if(!el)return;const{day,items,active}=todaysShows();document.getElementById('todayTitle').textContent=`${day}'s Programme`;el.innerHTML=items.map((x,i)=>row(x,i===active)).join('');const h=document.getElementById('heroNow'),n=document.getElementById('heroNext');if(active>=0){h.textContent=items[active][1];n.textContent=`${items[active][0]} • ${items[active][2]}`}else{h.textContent=items[0]?.[1]||'Online Radio';n.textContent=items[0]?`${items[0][0]} • ${items[0][2]}`:'Tune in online'}}
function renderSchedule(){const el=document.getElementById('fullSchedule');if(!el)return;const tabs=document.getElementById('dayTabs'),today=DAYS[new Date().getDay()],order=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];tabs.innerHTML=order.map(d=>`<button class="day-tab ${d===today?'selected':''}" data-day="${d}">${d}</button>`).join('');const draw=day=>{el.innerHTML=`<section class="day-panel"><div class="day-panel-head"><span class="section-label">${day.toUpperCase()}</span><h2>${day}</h2></div>${SCHEDULE[day].map(x=>row(x)).join('')}</section>`};draw(today);tabs.querySelectorAll('.day-tab').forEach(b=>b.addEventListener('click',()=>{tabs.querySelectorAll('.day-tab').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');draw(b.dataset.day)}))}
function renderPresenters(){const el=document.getElementById('presentersGrid');if(!el)return;const map=new Map();Object.entries(SCHEDULE).forEach(([day,shows])=>shows.forEach(([time,program,presenters])=>{if(presenters==='—')return;presenters.split(' & ').forEach(p=>{if(!map.has(p))map.set(p,[]);map.get(p).push(`${day} • ${program}`)})}));el.innerHTML=[...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,shows])=>`<article class="presenter-card"><div class="avatar">${initials(name)}</div><span class="presenter-label">ON AIR</span><h2>${esc(name)}</h2><p>${[...new Set(shows)].slice(0,3).map(esc).join('<br>')}</p></article>`).join('')}
function installPWA(){const btn=document.getElementById('installBtn');if(!btn)return;let promptEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;btn.classList.add('show');btn.onclick=async()=>{if(promptEvent){promptEvent.prompt();await promptEvent.userChoice;promptEvent=null;btn.classList.remove('show')}}});window.addEventListener('appinstalled',()=>btn.classList.remove('show'))}
document.addEventListener('DOMContentLoaded',()=>{shell();renderToday();renderSchedule();renderPresenters();installPWA();document.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',togglePlayer));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});
